### ISSUE TITLE
Make the crate `no_std`

### ISSUE THREAD

**Issue by llogiq** [llogiq/compact_arena#1]
At least TinyArena and NanoArena should be no_std. We could add two features (`no_std` and `alloc`) to make the crate usable in those settings. The former makes the crate `no_std` and the latter enables the SmallArena type using the alloc crate for no_std+alloc usage.

**Comment by kpp** [comment]
Features should add functionality not restrict it. So in case of no_std/std you will have to add `std` feature to enable std functionality.

take a look at https://www.reddit.com/r/rust/comments/49hlsf/no_std_library_optionally_depending_onusing_std/d0rxllu?utm_source=share&utm_medium=web2x

**Comment by llogiq** [comment]
You're right. An `alloc` default feature should be sufficient.
