### ISSUE TITLE
in_arena!($arena / 0, $e)

### ISSUE THREAD

**Issue by kpp** [llogiq/compact_arena#12]
What behavior should be for `in_arena!(arena/0,{})`? Division by zero?

**Comment by llogiq** [comment]
It should create an arena with an initial capacity of zero. As it does today.

**Comment by llogiq** [comment]
Revisiting this, perhaps documenting this might be a good idea.

**Comment by llogiq** [comment]
As the current version contains documentation for this behavior, I'm going to close this.
